version: "3"
services:

  http:
    image: ghcr.io/linuxserver/bookstack
    container_name: ${APP_NAME}_http
    restart: unless-stopped
    volumes:
      - ./data/http:/config
    ports:
      - 127.0.0.1:${APP_PORT}:80
    depends_on:
      - database
    env_file:
      - .env
      - .env.local

  database:
    image: ghcr.io/linuxserver/mariadb
    container_name: ${APP_NAME}_mysql
    restart: unless-stopped
    volumes:
      - ./data/mysql:/config
    env_file:
      - .env
      - .env.local
